### PR TITLE
Fix scrolling issues when going to different pages

### LINKED ISSUE #95: Scroll Reset Component is not functioning, when switching to different routes
While switching to a different route
The scroll postion is expected to move to top ( window.scrollTo(0, 0) )
But it remains fixed and does not work the way it was expected in the function

### PR DESCRIPTION
**Pull request by Abhishek-kumar09**
Fixed scroll reset issues with pages
Fixes #95

### CODE REVIEW

File: src/Routes.js [hunk 1]
```diff
@@ -109,38 +140,6 @@ const renderRoutes = () => (
...
-            <MainLayout>
-              <CoursesView {...props} />
-            </MainLayout>
-          </>
-        )}
-      />
-
-      <Route
-        path="/bootcamp"
-        render={props => (
```
Comment (Abhishek-kumar09) [inline src/Routes.js:126]: Just aligned routes so that homepage routes are placed together.

**Review by KeenWarrior — APPROVED** [review]
